refactor: 전체적인 backend refactoring
boostcampwm-2021/web04-canyoufixme pull request #172
Opened 2021-11-30 13:08 UTC by longnh214

## 진행 사항 요약
- 문자열들을 상수로 분리
- api url 일부 변경
- 공통된 함수 분리
- 공통된 상수 분리
- 미들웨어 함수 분리(setHeader, isLogin)
- response statusCode 지정

2021-11-30 17:30 UTC, Xvezda requested changes

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/app.ts
> +
세심한 개행이 좋은것 같습니다 :+1:

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/app.ts
> +import { COOKIE_MAX_AGE, COOKIE_SECRET } from './util/constant';
`./middlewares`와 `./settings`는 복수형이지만, `./controller`, `./util`은 단수형으로 작성하게 된 기준이 있을지 궁금합니다

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/util/common.ts
> +const isProduction = process.env.NODE_ENV === 'production';
해당 변수를 export 하여 https://github.com/boostcampwm-2021/web04-canyoufixme/blob/d6e85d98f0ed52c41713fd76ca999262567fb6f9/packages/backend/src/app.ts#L27 라인에서 활용하는것도 괜찮아 보입니다.

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/util/constant.ts
> +export const COOKIE_MAX_AGE = 1000 * 3600 * 12;
바로 위에 선언한 `SEC` 상수를 사용하여 `SEC * 3600 * 12` 형태로 작성하는것은 어떨까요?

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/controller/statisticController.ts
> +router.get('/most-submits', mostSubmitProblems);
`/submits/count`와 유사하게 `/submits/most`로 가져오는것은 어떨까요?

2021-11-30 17:30 UTC, Xvezda commented on packages/backend/src/service/loginService.ts
> +  res.status(301).redirect(`${process.env.ORIGIN_URL}`);
301 코드는 Moved Permanently 라는 의미인데 이 경우에 적합한 코드일까요?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages

2021-12-01 01:06 UTC, Winters0727 commented on packages/backend/src/app.ts
> +  secret: COOKIE_SECRET,
세션 시크릿 키를 일반 변수 파일에서 관리하기 보다는 환경 변수로 관리하는 것이 더 좋을 것 같습니다.

2021-12-01 01:11 UTC, longnh214 commented on packages/backend/src/controller/statisticController.ts
> +router.get('/most-submits', mostSubmitProblems);
@dlckdduq1107

2021-12-01 01:12 UTC, longnh214 commented on packages/backend/src/util/common.ts
> +const isProduction = process.env.NODE_ENV === 'production';
👍🏻👍🏻👍🏻

2021-12-01 01:29 UTC, dlckdduq1107 commented on packages/backend/src/controller/statisticController.ts
> +router.get('/most-submits', mostSubmitProblems);
그게 좋을것 같네요!

2021-12-01 01:30 UTC, dlckdduq1107 commented on packages/backend/src/app.ts
> +import { COOKIE_MAX_AGE, COOKIE_SECRET } from './util/constant';
단수형이 나을것 같습니다!

2021-12-01 06:40 UTC, Winters0727 approved these changes
수고하셨습니다. 👍🏼

2021-12-01 06:49 UTC, dlckdduq1107 approved these changes
확인완료입니다!

2021-12-01 07:00 UTC, Xvezda approved these changes
👍

2021-12-01 07:00 UTC, merged