feat: 문제와 문제 코드에 대한 API 개발
boostcampwm-2021/web04-canyoufixme pull request #65
Opened 2021-11-09 12:36 UTC by longnh214

## 진행 사항
- `Problem` 리스트 조회 API 개발
- `ProblemCode` 문제에 대한 코드 조회 API 개발
- data type 수정

## 참고 사항
- `.env.development`는 노션 `백엔드 데이터 타입` 페이지 안에

Resolved #46 #47 #49

2021-11-09 12:47 UTC, Xvezda requested changes

2021-11-09 12:47 UTC, Xvezda commented on packages/backend/src/controller/problemController.ts
> +router.get('/list', getList);
@boostcampwm-2021/team-1 
`/list` 같은 주소에 대해서 list 대신 복수형을 사용해야 한다는 의견이 있던데 어떤게 좋을까요? 🤔 
e.g.) `GET /api/problems`

참고: https://stackoverflow.com/a/6846057

2021-11-09 12:53 UTC, longnh214 commented on packages/backend/src/controller/problemController.ts
> +router.get('/list', getList);
좋은 방법! 내일 반영 하겠슴다! 🙌🏻👨🏻‍💻

2021-11-10 01:53 UTC, Xvezda commented on packages/backend/src/controller/problemController.ts
> +router.get('/list', getList);
스크럼 결과: 복수 채택

2021-11-10 01:53 UTC, Xvezda approved these changes

2021-11-10 01:54 UTC, dlckdduq1107 commented on packages/backend/src/app.ts
> +app.use('/api/debug', problemCodeController);
문제 코드를 가져오는 API 명이 debug로 하는게 맞을지 의견을 물어보고 싶네요..!

2021-11-10 01:59 UTC, longnh214 commented on packages/backend/src/app.ts
> +app.use('/api/debug', problemCodeController);
현재 테이블 이름은 `programCode`이지만 programcode를 url에 담기에는 너무 길어서 `debug`로 기입했습니다.
('기존에 debug로 되어 있어서 혼동이 없도록 하기 위해서'의 이유도 있습니다.)

2021-11-10 04:50 UTC, Winters0727 approved these changes
API 엔드포인트 관련 의견 좋았습니다. 추후에 더 의논한 뒤에 `dev` 브랜치에 반영하도록 합시다.

2021-11-10 04:50 UTC, Winters0727 commented on packages/backend/src/app.ts
> +app.use('/api/debug', problemCodeController);
저는 문제에 대한 코드도 문제의 하위 데이터에 포함되기 때문에 `problemController`와 `problemCodeController`를 통합해도 무방하다고 생각합니다.

2021-11-10 05:33 UTC, Winters0727 approved these changes
API 엔드포인트 변경된 것 확인했습니다.

2021-11-10 05:33 UTC, dlckdduq1107 approved these changes
수정사항 반영 굿!

2021-11-10 05:37 UTC, Xvezda requested changes

2021-11-10 05:37 UTC, Xvezda commented on packages/frontend/src/pages/ListPage/index.tsx
> +      .then(async res => await res.json())
불필요한 키워드가 들어가있네요

2021-11-10 05:37 UTC, longnh214 commented on packages/frontend/src/pages/ListPage/index.tsx
> +      .then(async res => await res.json())
확인했습니다.

2021-11-10 05:38 UTC, dlckdduq1107 commented on packages/frontend/src/pages/ListPage/index.tsx
> +      .then(async res => await res.json())
매의 눈 인정합니다!

2021-11-10 05:38 UTC, Xvezda approved these changes

2021-11-10 05:38 UTC, Winters0727 approved these changes

2021-11-10 05:38 UTC, dlckdduq1107 approved these changes
컴펌입니다! 사소한 사항 수정 굿 입니다!

2021-11-10 05:38 UTC, merged