fix: Backtick 입력시 동작하지 않는 문제 수정 및 iframe 화면 노출 방지
boostcampwm-2021/web04-canyoufixme pull request #90
Opened 2021-11-15 09:05 UTC by Xvezda

Backtick을 escape 처리

Fixes #74

fix: iframe의 화면 노출 방지

Resolves #75

2021-11-15 09:11 UTC, longnh214 submitted a review, later dismissed
replaceAll을 안해도 괜찮을까요???

2021-11-15 09:11 UTC, dlckdduq1107 approved these changes
백틱 수정 , iframe 안보이게 수정 확인입니다!

2021-11-15 09:14 UTC, dlckdduq1107 requested changes
낙훈님 말처럼 replaceAll이 좋아 보인다고 생각합니다!

2021-11-15 09:28 UTC, Xvezda commented
> replaceAll을 안해도 괜찮을까요???

`/.../g` 형태의 정규식을 사용해서 괜찮겠지만 의미를 명확하게, 또한 `g` 플래그를 강제하기 위해서 `replaceAll`을 사용하는게 더 적합해보입니다.

2021-11-15 10:11 UTC, longnh214 approved these changes
앗 `replaceAll` 반영 감사합니다!
정규식으로 이미 replace가 적용이 된 것이었군요! :)

2021-11-16 01:31 UTC, Winters0727 approved these changes
backtick 제거 및 iframe를 보이지 않게 처리한 점 확인했습니다.

2021-11-16 01:33 UTC, dlckdduq1107 approved these changes
변경확인입니다!

2021-11-16 01:37 UTC, merged