refactor: 문제 리스트 API에 offset과 limit 쿼리 적용
boostcampwm-2021/web04-canyoufixme pull request #91
Opened 2021-11-15 09:06 UTC by Winters0727

- 무한 스크롤 기능을 적용하기 위해 문제 리스트를 불러오는 과정에서 query로 limit와 offset 쿼리를 적용할 수 있도록 변경

2021-11-15 09:12 UTC, longnh214 submitted a review, later dismissed
무한 스크롤을 적용하기 위한 사전 준비이군요. :)

2021-11-15 09:13 UTC, Xvezda requested changes
두가지 문제가 있습니다
- `?limit=`값은 `?offset=` 값이 없어도 동작하는데, `?offset=` 값만 지정된 경우 백엔드 에러가 발생하는 문제
- 음수 값이 입력된 경우 오류가 발생

2021-11-15 09:15 UTC, Xvezda commented
@Xvezda +추가) 쿼리 기능이 추가 된 것이므로 `feat:` 태그가 더 적절하지 않을까요?

2021-11-16 01:20 UTC, longnh214 approved these changes
typeorm이 명명 규칙을 모호하게 지은 것이군요.
`offset`과 `limit`가 익숙합니다.

2021-11-16 01:34 UTC, Winters0727 commented
- `limit`와 `offset`이 숫자가 아니거나 음수인 경우 기본값을 0으로 처리
- 기본값이 0으로 설정되었기 때문에 `limit`가 없는 `offset`도 에러 없이 모든 데이터를 가져오게 처리

2021-11-16 01:39 UTC, dlckdduq1107 submitted a review, later dismissed
offset, limit 수정 확인했습니다!

2021-11-16 09:29 UTC, Xvezda approved these changes
👍

2021-11-16 09:29 UTC, Winters0727 commented
- `limit`의 기본값이 0일 경우에 모든 데이터를 가져오게 되서 기본값을 10으로 변경
- 응답 시에 상태코드 추가 (백엔드에서 응답 넘겨줄 때 상태코드도 같이 넘겨주세요.)
- 에러 핸들링 처리

2021-11-16 09:38 UTC, longnh214 approved these changes

2021-11-16 13:02 UTC, merged