feat: 문제 리스트 페이지 무한 스크롤 기능 추가
boostcampwm-2021/web04-canyoufixme pull request #99
Opened 2021-11-16 10:04 UTC by Winters0727

- 문제 리스트 페이지 무한 스크롤 기능 추가

2021-11-16 12:17 UTC, longnh214 submitted a review, later dismissed
무한 스크롤 API를 이용해서 잘 구현하셨습니다.
`incOffset`은 무슨 뜻일까요!

2021-11-16 12:44 UTC, Winters0727 commented
> 무한 스크롤 API를 이용해서 잘 구현하셨습니다. `incOffset`은 무슨 뜻일까요!

`Inc`rease `Offset`의 줄임말입니다.

2021-11-16 12:50 UTC, longnh214 commented
> > 무한 스크롤 API를 이용해서 잘 구현하셨습니다. `incOffset`은 무슨 뜻일까요!
> 
> `Inc`rease `Offset`의 줄임말입니다.

감사합니다 :)

2021-11-16 17:11 UTC, dlckdduq1107 requested changes
나중에 reducer 파일을 분리하면 좋을 것 같네요!

2021-11-16 17:11 UTC, dlckdduq1107 commented on packages/frontend/src/pages/ListPage/index.tsx
> +  const [state, dispatch] = useReducer(paginationReducer, {
state 보다 더 직관적인 이름이 있다면 좋을 거 같아요!

2021-11-16 17:11 UTC, dlckdduq1107 commented on packages/frontend/src/pages/ListPage/index.tsx
> +  const ioRef: MutableRefObject<IntersectionObserver | undefined> = useRef();
ioRef라는게 어떤 의미인가요?

2021-11-16 17:11 UTC, dlckdduq1107 commented on packages/frontend/src/pages/ListPage/index.tsx
> +          console.log(
console.log는 지워도 될듯 합니다!

2021-11-17 01:29 UTC, longnh214 approved these changes
변경 사항 확인했습니다.

2021-11-17 01:30 UTC, dlckdduq1107 approved these changes
변경사항 반영 확인입니다!

2021-11-17 01:38 UTC, merged